apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-unit-testing-pv
  labels:
    type: local
    app: postgres-unit-testing
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
