apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-unit-testing-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
