apiVersion: v1
kind: Service
metadata:
  name: postgres-unit-testing-service
  labels:
    app: postgres-unit-testing
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres-unit-testing
